export interface LeaveModel {
    id?: number; // Optional because it is generated by the backend
    employeeId?: number; // Filled automatically in the backend
    departmentId?: number; // Filled automatically in the backend
    leaveType: string; // Required when submitting the form
    reason: string; // Required when submitting the form
    startDate: Date; // Required when submitting the form
    endDate: Date; // Required when submitting the form
    status?: string; // Defaults to "Pending"
    decisionBy?: number; // Filled when a manager approves/rejects
    decisionDate?: Date; // Filled when a manager approves/rejects
    employeeName:string;
    createdAt:Date
  }